/* eslint-disable prettier/prettier */
import { BaseEntity, Entity, PrimaryGeneratedColumn, Column, ManyToOne } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import { TaskStatus } from './helpers/task-status.enum';
import { User } from 'src/auth/user.entity';

// defining the Task entity with the parameters id, title, description and status
@Entity()
export class Task extends BaseEntity {
  // id is the auto generated primary key
  @ApiProperty({
    description: 'ID único de la tarea',
    example: 1
  })
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty({
    description: 'Título de la tarea',
    example: 'Completar proyecto de NestJS'
  })
  @Column()
  title: string;

  @ApiProperty({
    description: 'Descripción detallada de la tarea',
    example: 'Implementar autenticación JWT y documentación Swagger'
  })
  @Column()
  description: string;

  @ApiProperty({
    description: 'Estado actual de la tarea',
    enum: TaskStatus,
    example: TaskStatus.OPEN
  })
  @Column()
  status: TaskStatus;

  @ApiProperty({
    description: 'Usuario propietario de la tarea',
    type: () => User
  })
  @ManyToOne(type => User, user => user.tasks, { eager: false })
  user: User;

  @ApiProperty({
    description: 'ID del usuario propietario',
    example: 1
  })
  @Column()
  userId: number; // auto generated by typeorm
}